/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wqa.form.main;

import java.awt.Color;
import java.util.concurrent.locks.ReentrantLock;
import javax.swing.JFrame;
import javax.swing.JProgressBar;
import wqa.system.WQAPlatform;

/**
 *
 * @author chejf
 */
public class ProcessDialog extends javax.swing.JDialog {
  
    /**
     * Creates new form CommonDialog
     */
    public ProcessDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //去除对话框标题栏
        this.getRootPane().setWindowDecorationStyle(0);

        initComponents();

        this.setResizable(false);
        //this.
        //this.setVisible(false);
        //居中显示
        setLocationRelativeTo(parent);

        //透明对话框
        this.getRootPane().setOpaque(false);
        this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        this.setBackground(new Color(0, 0, 0, 0));

        //this.ProgressBar.setUI((ProgressBarUI) javax.swing.UIManager.set);
    }

    public JProgressBar GetProcessBar() {
        return this.ProgressBar;
    }

    public void Close() {
        this.dispose();
    }

    
    // <editor-fold defaultstate="collapsed" desc="进度条接口">
    private static ProcessDialog pdialog;
    private static ReentrantLock process_lock = new ReentrantLock();

    public static ProcessDialog GetGlobalProcessBar() {
        return pdialog;
    }

    public static void ApplyGlobalProcessBar() {
        process_lock.lock();
        try {
            if (pdialog == null) {
                pdialog = new ProcessDialog(MainForm.main_parent, true);
                pdialog.GetProcessBar().setMaximum(100);
                pdialog.GetProcessBar().setMinimum(0);
                WQAPlatform.GetInstance().GetThreadPool().submit(new Runnable() {
                    @Override
                    public void run() {
                        //pdialog.setUndecorated(true);
                        pdialog.setVisible(true);
                    }
                });

            }
        } finally {
            process_lock.unlock();
        }
    }

    public static void ReleaseGlobalProcessBar() {
        process_lock.lock();
        try {
            if (pdialog != null) {
                pdialog.Close();
                pdialog = null;
            }
        } finally {
            process_lock.unlock();
        }
    }
    // </editor-fold>  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    // End of variables declaration//GEN-END:variables

}
