/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wqa.form.config.cal;

import java.awt.Dimension;

/**
 *
 * @author chejf
 */
public class CalItem extends javax.swing.JPanel {

    /**
     * Creates new form CalItem
     */
    public CalItem(int index) {
        initComponents();

        Label_Test.setText("标" + index + ":");
        this.Label_Test.setMinimumSize(new Dimension(56, 15));
        this.Label_Test.setMaximumSize(new Dimension(56, 15));
        this.Label_Test.setPreferredSize(new Dimension(56, 15));
    }

    public void SetValue(float ora_data, float test_data) {
        if (!this.isSet) {
            if (this.TextField_test.isEditable()) {
                this.TextField_test.setText(String.valueOf(test_data));
            }
            this.TextField_ora.setText(String.valueOf(ora_data));
        }
    }

    private boolean isSet;

    public boolean IsSet() {
        return this.isSet;
    }

    public float[] GetInputData() {
        return new float[]{
            Float.valueOf(this.TextField_ora.getText()),
            this.TextField_test.isEditable() ? Float.valueOf(this.TextField_test.getText()) : 0};
    }

    public void SetTestLable(String value) {
//        this.Label_Test.setText(value);
        this.TextField_test.setEditable(false);
        this.TextField_test.setText(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_test = new javax.swing.JTextField();
        TextField_ora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Label_Test = new javax.swing.JLabel();
        ToggleButton_Set = new javax.swing.JToggleButton();

        jLabel1.setText("原始值:");

        Label_Test.setText("标:");

        ToggleButton_Set.setText("停止");
        ToggleButton_Set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton_SetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Label_Test, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_test, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(TextField_ora, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(ToggleButton_Set, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_ora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Test)
                    .addComponent(jLabel1)
                    .addComponent(ToggleButton_Set))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ToggleButton_SetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton_SetActionPerformed
        this.isSet = this.ToggleButton_Set.isSelected();
        if (this.ToggleButton_Set.isSelected()) {
            this.ToggleButton_Set.setText("测量");
        } else {
            this.ToggleButton_Set.setText("停止");
        }
    }//GEN-LAST:event_ToggleButton_SetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Test;
    private javax.swing.JTextField TextField_ora;
    private javax.swing.JTextField TextField_test;
    private javax.swing.JToggleButton ToggleButton_Set;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
