/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wqa.form.monitor;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import org.jfree.ui.RectangleInsets;
import wqa.chart.DataChart;

/**
 *
 * @author chejf
 */
public class MChartPane extends javax.swing.JPanel {

    private JComboBox<String> combox = new JComboBox<>();
    private DataChart datachart = new DataChart();
    private JLabel name = new JLabel("显示曲线:");

    /**
     * Creates new form MChartPane
     */
    int c_with = 100;
    int c_heigth = 20;
    int vgap = 5;
    int hgap = 20;

    public MChartPane() {
        initComponents();

        //设置上下左右留白
        this.datachart.dataChart.setPadding(new RectangleInsets(25d, 5d, 5d, 10d));
        name.setHorizontalAlignment(JLabel.RIGHT);
        name.setForeground(Color.black);

        setLayout(new BorderLayout());
        JLayeredPane layeredPane = new JLayeredPane();
        layeredPane.add(datachart, new Integer(1));
        layeredPane.add(combox, new Integer(2));
        layeredPane.add(name, new Integer(3));

        this.add(layeredPane, BorderLayout.CENTER);
        this.addComponentListener(new ComponentListener() {
            @Override
            public void componentResized(ComponentEvent ce) {
                int width = MChartPane.this.getWidth();
                int height = MChartPane.this.getHeight();
                datachart.setBounds(0, 0, width, height);
                datachart.updateUI();
                combox.setBounds(width - c_with - hgap, vgap, c_with, c_heigth);
                name.setBounds(width - 2*(c_with +  hgap), vgap, c_with, c_heigth);
            }

            @Override
            public void componentMoved(ComponentEvent ce) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void componentShown(ComponentEvent ce) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void componentHidden(ComponentEvent ce) {
//                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    public JComboBox<String> GetComboBox() {
        return this.combox;
    }

    public DataChart GetChartPane() {
        return this.datachart;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
