/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wqa.form.monitor;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author chejf
 */
public class MTRow extends javax.swing.JPanel {

    /**
     * Creates new form MTRow
     */
    public MTRow() {
        initComponents();

//        this.setBackground(new Color(227, 230, 235));
        this.setOpaque(false);
        
        this.Label_Data.setForeground(new Color(34, 55, 95));
        this.Label_Data.setFont(new Font("Microsoft YaHei", 0, 40));
        
        this.Label_Data.setHorizontalAlignment(JLabel.CENTER);
        this.Label_Name.setForeground(new Color(34, 55, 95));
        this.Label_Name.setFont(new Font("Microsoft YaHei", 0, 15));
        this.Label_Name.setHorizontalAlignment(JLabel.CENTER);
        this.Label_Name.setVerticalAlignment(JLabel.BOTTOM);
        this.Label_Range.setForeground(new Color(34, 55, 95));
        this.Label_Range.setFont(new Font("Microsoft YaHei", 0, 15));
        this.Label_Range.setHorizontalAlignment(JLabel.CENTER);
        this.Label_Range.setVerticalAlignment(JLabel.TOP);
        this.Label_Unit.setForeground(new Color(34, 55, 95));
        this.Label_Unit.setFont(new Font("Microsoft YaHei", 0, 15));
        this.Label_Unit.setHorizontalAlignment(JLabel.LEFT);
        this.Label_Unit.setVerticalAlignment(JLabel.TOP);
    }
    
    public void SetData(String name, String range, String data, String unit) {
        this.Label_Name.setText(name);
        this.Label_Range.setText(range);
        this.Label_Data.setText(data);
        this.Label_Unit.setText(unit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Data = new javax.swing.JLabel();
        Label_Name = new javax.swing.JLabel();
        Label_Range = new javax.swing.JLabel();
        Label_Unit = new javax.swing.JLabel();

        Label_Data.setText("0.0000");

        Label_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Name.setText("- -");
        Label_Name.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Label_Name.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Label_Range.setText("- -");

        Label_Unit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Unit.setText("- -");
        Label_Unit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Label_Unit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_Range, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(Label_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Data, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(Label_Unit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Label_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Range, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Label_Unit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Label_Data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Data;
    private javax.swing.JLabel Label_Name;
    private javax.swing.JLabel Label_Range;
    private javax.swing.JLabel Label_Unit;
    // End of variables declaration//GEN-END:variables
}
