/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wqa.form.log;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.JTableHeader;
import wqa.bill.log.DevLog;
import wqa.control.data.DevID;

/**
 *
 * @author chejf
 */
public class DevLogForm extends javax.swing.JDialog {

    /**
     * Creates new form CommonDialog
     *
     * @param parent
     * @param name
     * @param modal
     */
    public DevLogForm(java.awt.Frame parent, boolean modal, String name) {
        super(parent, modal);
        initComponents();
        //居中显示
        setLocationRelativeTo(parent);

        this.setTitle(name);

        this.getContentPane().setBackground(new Color(34, 88, 149));

        this.setAlwaysOnTop(true);

//        this.LogSpane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        this.LogSpane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    }

    public void InitLog(DevID devid) {
        ArrayList<String> ReadLog = DevLog.Instance().ReadLog(devid);
        this.DevLogTable.setModel(new AbstractTableModel() {
            @Override
            public String getColumnName(int i) {
                return "日志";
            }

            @Override
            public int getRowCount() {
                return ReadLog.size();
            }

            @Override
            public int getColumnCount() {
                return 1;
            }

            @Override
            public Object getValueAt(int i, int i1) {
                return ReadLog.get(i);
            }
        });
        this.DevLogTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        //找到所有比较历史记录中最宽列宽
        int maxcolum_width = LogSpane.getSize().width - 15;
        int col = 0;
        for (int i = 0; i < this.DevLogTable.getRowCount(); i++) {
            //更新列宽
            int row = i;
            //获取最新一列数据的宽度
            int preferedWidth = (int) DevLogTable.getCellRenderer(row, col).getTableCellRendererComponent(DevLogTable,
                    DevLogTable.getValueAt(row, col), false, false, row, col).getPreferredSize().getWidth();

            maxcolum_width = maxcolum_width > preferedWidth ? maxcolum_width : preferedWidth;
        }

        JTableHeader header = DevLogTable.getTableHeader();
        header.setResizingColumn(DevLogTable.getColumnModel().getColumn(col)); // 此行很重要
        //设置列宽为表格宽度和数据最大宽度里的最大值
        DevLogTable.getColumnModel().getColumn(col).setWidth(maxcolum_width);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogSpane = new javax.swing.JScrollPane();
        DevLogTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        DevLogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        LogSpane.setViewportView(DevLogTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogSpane, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogSpane, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DevLogTable;
    private javax.swing.JScrollPane LogSpane;
    // End of variables declaration//GEN-END:variables

}
