/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wqa.form.db;

import org.jfree.data.Range;

/**
 *
 * @author jiche
 */
public class ManualRangeDialog extends javax.swing.JDialog {

    /**
     * Creates new form ManualRangeDialog
     */
    public ManualRangeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(null);

        this.ManualY1_Lable.setText("最小值:");
        this.ManualY2_Lable.setText("最大值:");
        this.Button_ManualRangeOK.setText("确定");
    }

    public void SetCurrentRange(Range yrange) {
        this.TextField_Y1.setText(String.format("%.2f", yrange.getLowerBound()));
        this.TextField_Y2.setText(String.format("%.2f", yrange.getUpperBound()));
    }

    // <editor-fold defaultstate="collapsed" desc="坐标轴大小">  
    private Range yrange = null;

    public Range GetYRange() {
        return yrange;
    }
    // </editor-fold>

    private void GetValue() {
        try {
            double y1 = Double.valueOf(this.TextField_Y1.getText());
            double y2 = Double.valueOf(this.TextField_Y2.getText());
            if (y1 <= y2) {
                yrange = new Range(y1, y2);
            } else {
                return;
            }
        } catch (Exception ex) {
            return;
        }
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_Y1 = new javax.swing.JTextField();
        ManualY1_Lable = new javax.swing.JLabel();
        TextField_Y2 = new javax.swing.JTextField();
        ManualY2_Lable = new javax.swing.JLabel();
        Button_ManualRangeOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TextField_Y1.setText("0");

        ManualY1_Lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManualY1_Lable.setText("jLabel1");

        TextField_Y2.setText("0");

        ManualY2_Lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManualY2_Lable.setText("jLabel1");

        Button_ManualRangeOK.setText("OK");
        Button_ManualRangeOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ManualRangeOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManualY1_Lable, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(ManualY2_Lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Button_ManualRangeOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_Y2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(TextField_Y1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(5, 5, 5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManualY2_Lable)
                    .addComponent(TextField_Y2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManualY1_Lable)
                    .addComponent(TextField_Y1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_ManualRangeOK)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ManualRangeOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ManualRangeOKActionPerformed
        this.GetValue();
    }//GEN-LAST:event_Button_ManualRangeOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ManualRangeOK;
    private javax.swing.JLabel ManualY1_Lable;
    private javax.swing.JLabel ManualY2_Lable;
    private javax.swing.JTextField TextField_Y1;
    private javax.swing.JTextField TextField_Y2;
    // End of variables declaration//GEN-END:variables
}
